spring:
    config:
        activate:
            on-profile: gcloud

    datasource:
        url: jdbc:postgresql://google/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver

        hikari:
            maximum-pool-size: 5
            data-source-properties:
                socketFactory: com.google.cloud.sql.postgres.SocketFactory
                cloudSqlInstance: ${CLOUD_SQL_CONNECTION_NAME}
                useSSL: false

    flyway:
        url: jdbc:postgresql://google/${DATABASE_NAME}
        user: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}